CREATE TABLE KHACHHANG
(
	MaKH NVARCHAR(30) NOT NULL PRIMARY KEY,
	TenKH NVARCHAR(30),
	DiaChi NVARCHAR(30),
	DienThoai CHAR(11),
	Email NVARCHAR(30),
	LoaiKH NVARCHAR(30)
)
CREATE TABLE HOADON
(
	MaHD NVARCHAR(30) NOT NULL PRIMARY KEY,
	MaKH NVARCHAR(30),
	NgayLapHD DATETIME

	FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)
)
CREATE TABLE HANGHOA
(
	MaH NVARCHAR(30) NOT NULL PRIMARY KEY,
	TenH NVARCHAR(30),
	DonViTinh NVARCHAR(30),
	DonGia DECIMAL(6,3)
)
CREATE TABLE CHITIETHD
(
	MaHD NVARCHAR(30),
	MaH NVARCHAR(30),
	Soluong INT

	PRIMARY KEY(MaH, MaHD),
	FOREIGN KEY (MaH) REFERENCES HANGHOA(MaH),
	FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD)
)
