
CREATE TABLE ADMINS
(
	USERNAME NVARCHAR(30) PRIMARY KEY,
	PASSWORDS NVARCHAR(20),
	EMAIL VARCHAR(30),
	SODIENTHOAI CHAR(11)
)
CREATE TABLE KHACHHANG
(
	MaKH NVARCHAR(30) PRIMARY KEY, 
	TenKH NVARCHAR(20),
	SODIENTHOAI CHAR(11),
	EMAIL VARCHAR(20)
)
CREATE TABLE DONDATHANG
(
	SOHOADON VARCHAR(20) PRIMARY KEY,
	NGAYDATHANG DATETIME,
	MAKH NVARCHAR(30),
	THANHTOAN FLOAT

	FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)

)
CREATE TABLE LOAIMONAN(
	MALOAI VARCHAR(30) PRIMARY KEY,
	TENLOAI VARCHAR(30)
)
CREATE TABLE NHAHANG 
(
	MANHAHANG VARCHAR(30) PRIMARY KEY,
	TENNHAHANG VARCHAR(30),
	SODIENTHOAI CHAR(11)
)

CREATE TABLE MONAN
(
	MAMONAN VARCHAR(20) PRIMARY KEY,
	MALOAI VARCHAR(30),
	TENMONAN VARCHAR(30),
	PRICE FLOAT,
	MOTA VARCHAR(30),
	MANHAHANG VARCHAR(30)

	FOREIGN KEY (MALOAI) REFERENCES LOAIMONAN(MALOAI),
	FOREIGN KEY (MANHAHANG) REFERENCES NHAHANG(MANHAHANG)
)
CREATE TABLE CHITIETDATHANG
(
	SOHOADON VARCHAR(20),
	MAMONAN VARCHAR(20),
	DONGIA FLOAT,
	SOLUONG INT

	PRIMARY KEY (SOHOADON,MAMONAN),
	FOREIGN KEY (SOHOADON) REFERENCES DONDATHANG(SOHOADON),
	FOREIGN KEY (MAMONAN) REFERENCES MONAN(MAMONAN)
)
