CREATE TABLE SINHVIEN
(
	MaSV VARCHAR(30) NOT NULL PRIMARY KEY,
	HoTen VARCHAR(30),
	DiaChi VARCHAR(30)
)

CREATE TABLE MONHOC
(
	MaMH VARCHAR(30) NOT NULL PRIMARY KEY,
	TenMH VARCHAR(30)
)

CREATE TABLE BANGDIEM
(
	MaSV VARCHAR(30),
	MaMH VARCHAR(30),
	SoDiem INT

	PRIMARY KEY (MaSV, MaMH),
	FOREIGN KEY (MaSV) REFERENCES SINHVIEN(MaSV),
	FOREIGN KEY (MaMH) REFERENCES MONHOC(MaMH)
)

INSERT INTO SINHVIEN VALUES ('MS1','HT1','DC1')
INSERT INTO SINHVIEN VALUES ('MS2','HT2','DC2')
INSERT INTO SINHVIEN VALUES ('MS3','HT3','DC1')
INSERT INTO SINHVIEN VALUES ('MS4','HT4','DC2')
INSERT INTO SINHVIEN VALUES ('MS5','HT5','DC1')

INSERT INTO MONHOC VALUES ('A','MH1')
INSERT INTO MONHOC VALUES ('B','MH2')
INSERT INTO MONHOC VALUES ('C','NH3')
INSERT INTO MONHOC VALUES ('D', 'NH2')
INSERT INTO MONHOC VALUES ('E','NH3')

SELECT DISTINCT MaSV FROM BANGDIEM WHERE MaMH='A'
UNION 
SELECT
DISTINCT MaSV FROM BANGDIEM WHERE MaMH='B'