CREATE TABLE NHACUNGCAP
(
	MaNhaCC VARCHAR(30) NOT NULL PRIMARY KEY,
	TenNhaCC VARCHAR(30),
	DiaChi VARCHAR(30),
	SoDT CHAR(11),
	MaSoThue VARCHAR(30)
)

CREATE TABLE LOAIDICHVU
(
	MaLoaiDV VARCHAR(30) NOT NULL PRIMARY KEY,
	TenLoaiDV VARCHAR(30)
)

CREATE TABLE MUCPHI
(
	MaMP VARCHAR(30) NOT NULL PRIMARY KEY,
	DonGia VARCHAR(30),
	MoTa VARCHAR(30)
)

CREATE TABLE DONGXE
(
	DongXe VARCHAR(30) NOT NULL PRIMARY KEY,
	HangXe VARCHAR(30),
	SoChoNgoi INT
)

CREATE TABLE DANGKYCUNGCAP 
(
	MaDKCC VARCHAR(30) NOT NULL PRIMARY KEY,
	MaNhaCC VARCHAR(30),
	MaLoaiDV VARCHAR(30),
	DongXe VARCHAR(30),
	MaMP VARCHAR(30),
	NgayBatDauCungCap DATETIME,
	NgayKetThucCungCap DATETIME,
	SoluongXeDangKy INT

	FOREIGN KEY (MaNhaCC) REFERENCES NHACUNGCAP(MaNhaCC),
	FOREIGN KEY (MaLoaiDV) REFERENCES LOAIDICHVU(MaLoaiDV),
	FOREIGN KEY (DongXe) REFERENCES DONGXE(DongXe),
	FOREIGN KEY (MaMP) REFERENCES MUCPHI(MaMP)
)
