CREATE TABLE NHANVIEN
(
	MaNV VARCHAR(30) NOT NULL PRIMARY KEY,
	TenNV VARCHAR(30),
	NgaySinh DATETIME,
	SoDT VARCHAR(30)
)
CREATE TABLE KHACHHANG
(
	SoCMND VARCHAR(30) NOT NULL PRIMARY KEY,
	TenKH VARCHAR(30),
	TheKH DATETIME,
	SoDT VARCHAR(30)
)
CREATE TABLE HoaDon
(
	MaHoaDon VARCHAR(30) NOT NULL PRIMARY KEY,
	SoCMND VARCHAR(30),
	MaNV VARCHAR(30)

	FOREIGN KEY (SoCMND) REFERENCES KHACHHANG(SoCMND),
	FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
)
CREATE TABLE MatHang
(
	MaMatHang VARCHAR(30) NOT NULL PRIMARY KEY,
	Gia DECIMAL(6,3),
	TinhTrang VARCHAR(30)
)
CREATE TABLE SoLuongMuaHang
(
	MaMatHang VARCHAR(30) NOT NULL PRIMARY KEY,
	MaHoaDon VARCHAR(30),
	SoLuong INT,
	FOREIGN KEY (MaHoaDon) REFERENCES HOADON(MaHoaDon),
	FOREIGN KEY (MaMatHang) REFERENCES MatHang(MaMatHang)
)