CREATE TABLE KHACHHANG
(
	MaKH NVARCHAR(30) NOT NULL PRIMARY KEY,
	TenKH NVARCHAR(30),
	Email NVARCHAR(30),
	SoDT CHAR(30),
	Diachi NVARCHAR(30)
)

CREATE TABLE THANHTOAN
(
	MaTT NVARCHAR(30) NOT NULL PRIMARY KEY,
	PhuongthucTT NVARCHAR(30)
)

CREATE TABLE DONHANG
(
	MaDH NVARCHAR(30) NOT NULL PRIMARY KEY,
	MaKH NVARCHAR(30),
	MaTT NVARCHAR(30),
	NgayDat DATETIME,
	FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
	FOREIGN KEY (MaTT) REFERENCES THANHTOAN(MaTT)
)
CREATE TABLE DMSANPHAM
(
	MaDM NVARCHAR(100) NOT NULL PRIMARY KEY,
	TenDanhMuc NVARCHAR,
	MoTa NVARCHAR
)
CREATE TABLE SANPHAM
(
	MaSP NVARCHAR(30) NOT NULL PRIMARY KEY,
	MaDM NVARCHAR(30),
	TenSP NVARCHAR(30),
	GiaTien float,
	SoLuong INT,
	XuatXu NVARCHAR(30)
	FOREIGN KEY (MaDM) REFERENCES DMSANPHAM(MaDM)
)
CREATE TABLE CHITIETDONHANG
(
	MaDH NVARCHAR(30),
	MaSP NVARCHAR(30),
	SoLuong INT,
	TongTien float
	PRIMARY KEY(MaDH, MaSP),
	FOREIGN KEY (MaDH) REFERENCES DONHANG(MaDH),
	FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
)

INSERT INTO KHACHHANG VALUES ('KH001','Tran Van An','antv@gmail.com','0905123564','Lang Son')
INSERT INTO KHACHHANG VALUES('KH002','Phan Phuoc', 'phuocp@gmail.com','0932568984','Da Nang')
INSERT INTO KHACHHANG VALUES('KH003','Tran Huu Anh','anhth@gmail.com','0901865232','Ha Noi')

INSERT INTO DMSANPHAM VALUES ('DM01','Thoi Trang Nu','vay,ao danh cho nu') 
INSERT INTO DMSANPHAM VALUES ('DM02','Thoi trang Nam', 'quan danh cho nam')
INSERT INTO DMSANPHAM VALUES ('DM03','Trang suc','danh cho nu va nam')

INSERT INTO SANPHAM VALUES ('SP001','DM01','Dam Maxi',200,195000,'VN'), 
('SP002','DM01','Tui Da Mỹ',50,3000000,'HK'),
('SP003','DM02','Lac tay Uc',300,300000,'HQ')

INSERT INTO THANHTOAN VALUES ('TT01','Visa'),
('TT02','Master Card'),('TT03','JCB')

INSERT INTO DONHANG VALUES ('DH001','KH002','TT01','2014/10/20'),
('DH002','KH002','TT01','2015/5/15'),
('DH003','KH002','TT10','2015/04/20')

INSERT INTO CHITIETDONHANG VALUES ('DH001','SP002',3,56000),
('DH003','SP001',10,27444),
('DH002','SP002',10,67144)

--1.Tạo một khung nhìn có tên là V_KhachHang để thấy được thông tin của tất cả các đơn hàng có ngày 
--đặt hàng nhỏ hơn  ngày 06/15/2015 của những khách hàng có địa chỉ là "Da Nang"
create view V_KhachHang
AS
SELECT DONHANG.MaDH, DONHANG.MaKH, DONHANG.MaTT,DONHANG.NgayDat FROM DONHANG
INNER JOIN KHACHHANG ON DONHANG.MaKH= KHACHHANG.MaKH
WHERE (DONHANG.NgayDat<='06/15/2015' AND KHACHHANG.Diachi='Da Nang')
