
CREATE TABLE DMKHOA
(
	MaKhoa VARCHAR(50) PRIMARY KEY,
	TenKhoa VARCHAR(50)
)

CREATE TABLE DMNGANH
(
	MaNganh VARCHAR(50) PRIMARY KEY,
	TenNganh VARCHAR(50),
	MaKhoa VARCHAR(50),
	FOREIGN KEY (MaKhoa) REFERENCES DMKHOA(MaKhoa)
)

CREATE TABLE DMLOP
(
	MaLop VARCHAR(50) PRIMARY KEY,
	TenLop VARCHAR(50),
	MaNganh VARCHAR(50),
	KhoaHoc INT,
	HeDT VARCHAR(50),
	NamNhapHoc INT,
	FOREIGN KEY (MaNganh) REFERENCES DMNGANH(MaNganh)

)
CREATE TABLE DMHOCPHAN
(
	MaHP VARCHAR(50) PRIMARY KEY,
	TenHP VARCHAR(50),
	Sodvht VARCHAR(50),
	MaNganh VARCHAR(50),
	HocKy INT

	FOREIGN KEY (MaNganh) REFERENCES DMNGANH(MaNganh)
)

CREATE TABLE SINHVIEN
(
	MaSV VARCHAR(50) PRIMARY KEY,
	HoTen VARCHAR(50),
	MaLop VARCHAR(50),
	Gioitinh bit,
	Ngaysinh DATETIME,
	DiaChi VARCHAR(50)

	FOREIGN KEY (MaLop) REFERENCES DMLOP(MaLop)
)

CREATE TABLE DIEMHP
(
	MaSV VARCHAR(50),
	MaHP VARCHAR(50),
	DiemHP float,

	PRIMARY KEY (MaSV,MaHP),
	FOREIGN KEY (MaSV) REFERENCES SINHVIEN(MaSV),
	FOREIGN KEY (MaHP) REFERENCES DMHOCPHAN(MaHP)
)