CREATE TABLE LopTinChi
(
	MaTinChi VARCHAR(30) NOT NULL PRIMARY KEY,
	TenTinChi VARCHAR(30)
)
CREATE TABLE SINHVIEN
(
	MaSinhVien VARCHAR(30) NOT NULL PRIMARY KEY,
	TenSinhVien VARCHAR(30),
	GioiTinh VARCHAR(30)
	FOREIGN KEY (MaTinChi)  REFERENCES LopTinChi(MaTinChi)
)
CREATE TABLE LopSinhHoat
(
	MaLopSinhHoat VARCHAR(30) NOT NULL PRIMARY KEY,
	TenLopSinhHoat VARCHAR(30),
	MaSinhVien VARCHAR(30)
	FOREIGN KEY (MaSinhVien)  REFERENCES SinhVien(MaSinhVien)	
)
CREATE TABLE NGANH
(
	MaNganh VARCHAR(30) NOT NULL PRIMARY KEY,
	TenNganh VARCHAR(30),

	MaLopSinhHoat VARCHAR(30)
	 
	FOREIGN KEY (MaSinhVien)  REFERENCES SinhVien(MaSinhVien)	
	FOREIGN KEY (MaLopSinhHoat)  REFERENCES LopSinhHoat(MaLopSinhHoat)
)

CREATE TABLE MONHOC
(
	MaMonHoc VARCHAR(30) PRIMARY KEY,
	TenMonHoc VARCHAR(30)
	FOREIGN KEY (MaTinChi)  REFERENCES LopTinChi(MaTinChi)
	FOREIGN KEY (MaNganh)  REFERENCES NGANH(MaNganh)	
)
CREATE TABLE GIANGVIEN
(
	MaGiangVien VARCHAR(30) NOT NULL PRIMARY KEY,
	TenGiangVien VARCHAR(30),
	GioiTinh VARCHAR(30),
	MaMonHoc VARCHAR(30) 
	FOREIGN KEY (MaMonHoc) REFERENCES MONHOC (MaMonHoc) 
	FOREIGN KEY (MaTinChi) REFERENCES LopTinChi(MaTinChi)
)

CREATE TABLE BOMON
(
	MaBoMon VARCHAR(30) NOT NULL PRIMARY KEY,
	TenBoMon VARCHAR(30),
	Phong VARCHAR(30),
	MaNganh VARCHAR(30)
	FOREIGN KEY (MaNganh) REFERENCES NGANH (MaNganh), 
	FOREIGN KEY (MaGiangVien) REFERENCES GIANGVIEN(MaGiangVien) 

)
	
CREATE TABLE KHOA
(
	MaKhoa VARCHAR(30) NOT NULL PRIMARY KEY,
	TenKhoa VARCHAR(30),
	Phong VARCHAR(30),
	MaBoMon VARCHAR(30)

	FOREIGN KEY (MaBoMon) REFERENCES BOMON (MaBoMon) 
)

CREATE TABLE Diem
(
	MaSinhVien VARCHAR(30),
	MaMonHoc VARCHAR(30),
	MaTinChi VARCHAR(30),
	SoDiem INT
)
